### ISSUE TITLE
The default `notes_dir_path` seems wrong

### ISSUE THREAD

**Issue by kaste** [budlime/ProjectNotes#1]
You have the default `notes_dir_path` set to `...`.  But (on my machine) 

```
In [5]: os.path.isdir("...")
Out[5]: True
```

which is probably not what *you* expected here.  In turn that leads to an error

```
Traceback (most recent call last):
  File "C:\Dev\Sublime Text\Lib\python38\sublime_plugin.py", line 1654, in run_
    return self.run()
  File "C:\Users\honkytonk\AppData\Roaming\Sublime Text 3\Installed Packages\ProjectNotes.sublime-package\ProjectNotes.py", line 94, in run
  File "./python3.8/os.py", line 223, in makedirs 
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: '...\\hulahoop'
```

**Comment by budRich** [comment]
thanks for reporting this @kaste ! If i recall correctly i used "..." because i wanted a non existent directory as the default. I will look into a way of adding the actual default directory in a OS agnostic way, i think i know how.
